# Generated by Django 3.2.7 on 2021-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('task_check', models.BooleanField(default=False)),
                ('task_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
